import { AIModel, Category, Collection, Prompt, User } from './types';

export const AI_MODELS: AIModel[] = ['ChatGPT', 'Claude', 'Gemini', 'MidJourney', 'DALL-E'];
export const CATEGORIES: Category[] = ['Education', 'Coding', 'Business', 'Art', 'Marketing', 'Fun'];

export const MOCK_USERS: User[] = [
  { id: 'u1', name: 'Alex Doe', avatar: 'https://i.pravatar.cc/150?u=u1', bio: 'Prompt engineering enthusiast.', badges: ['Prompt Master', 'Top Creator'], submittedPrompts: ['p1', 'p3', 'p5'], purchasedCollections: ['c2'], savedPrompts: ['p2'], createdCollections: ['c1', 'c3'] },
  { id: 'u2', name: 'Jane Smith', avatar: 'https://i.pravatar.cc/150?u=u2', bio: 'AI Artist and developer.', badges: ['Community Star'], submittedPrompts: ['p2', 'p4', 'p6', 'p7'], purchasedCollections: [], savedPrompts: [], createdCollections: ['c2'] },
  { id: 'u3', name: 'Sam Wilson', avatar: 'https://i.pravatar.cc/150?u=u3', submittedPrompts: [], purchasedCollections: [], savedPrompts: [], createdCollections: [] },
];

export const MOCK_PROMPTS: Prompt[] = [
  {
    id: 'p1',
    title: 'Ultimate Essay Writing Assistant',
    prompt: 'Act as an expert academic writer. I will provide you with a topic and key points. Your task is to structure a compelling five-paragraph essay with a clear introduction, three supporting body paragraphs, and a strong conclusion. Ensure smooth transitions and sophisticated vocabulary.',
    description: 'A powerful prompt to generate well-structured essays on any topic. Perfect for students and researchers.',
    author: MOCK_USERS[0],
    category: 'Education',
    tags: ['Essay Writing', 'Academic', 'Students'],
    upvotes: 125,
    downvotes: 5,
    createdAt: '2023-10-26T10:00:00Z',
    model: 'ChatGPT',
    isPublic: true,
  },
  {
    id: 'p2',
    title: 'Photorealistic Sci-Fi Cityscape',
    prompt: 'cinematic still of a sprawling cyberpunk cityscape at night, neon signs reflecting on wet asphalt, flying vehicles whizzing by, towering holographic advertisements, volumetric lighting, photorealistic, octane render, trending on artstation --ar 16:9 --v 5.2',
    description: 'Generate breathtaking, detailed sci-fi cityscapes with a cinematic feel using MidJourney.',
    author: MOCK_USERS[1],
    category: 'Art',
    tags: ['MidJourney', 'Sci-Fi', 'Art'],
    upvotes: 230,
    downvotes: 3,
    createdAt: '2023-10-25T14:30:00Z',
    model: 'MidJourney',
    isPublic: true,
  },
  {
    id: 'p3',
    title: 'Python Code Refactoring Expert',
    prompt: 'You are a senior Python developer specializing in clean code and refactoring. I will provide a Python script. Your task is to analyze it, identify areas for improvement, and provide a refactored version. Explain the changes you made and why they improve the code\'s readability, performance, and maintainability.',
    description: 'Submit your Python scripts to get expert feedback and refactoring suggestions to improve your code quality.',
    author: MOCK_USERS[0],
    category: 'Coding',
    tags: ['Python', 'Developer', 'Refactoring'],
    upvotes: 98,
    downvotes: 2,
    createdAt: '2023-10-24T09:00:00Z',
    model: 'Gemini',
    isPublic: true,
  },
   {
    id: 'p4',
    title: 'Social Media Content Calendar',
    prompt: 'Create a comprehensive social media content calendar for one month for a new sustainable fashion brand. The target audience is millennials who are environmentally conscious. Include post ideas for Instagram (feed, stories, reels), Facebook, and Twitter. Specify the content format (e.g., image, video, carousel), a catchy caption, and relevant hashtags for each post.',
    description: 'A detailed prompt to generate a full month of social media content, tailored for a specific brand and audience.',
    author: MOCK_USERS[1],
    category: 'Marketing',
    tags: ['Social Media', 'Marketing', 'Content Strategy'],
    upvotes: 150,
    downvotes: 7,
    createdAt: '2023-10-27T11:00:00Z',
    model: 'Claude',
    isPublic: true,
  },
  {
    id: 'p5',
    title: 'Interactive History Lesson Plan',
    prompt: 'Design an interactive lesson plan for a 10th-grade history class on the topic of the Silk Road. The lesson should be 60 minutes long and include a warm-up activity, a main interactive component (e.g., a role-playing simulation, a virtual tour), and an assessment. The goal is to make the learning process engaging and memorable. Provide all necessary materials and instructions.',
    description: 'Generate a creative and engaging history lesson plan to captivate students.',
    author: MOCK_USERS[0],
    category: 'Education',
    tags: ['Lesson Plan', 'History', 'Education'],
    upvotes: 85,
    downvotes: 4,
    createdAt: '2023-10-28T09:30:00Z',
    model: 'Gemini',
    isPublic: true,
  },
  {
    id: 'p6',
    title: 'Minimalist Logo Design Concepts',
    prompt: 'Generate 5 minimalist logo concepts for a tech startup called "Synapse". The company focuses on AI-powered data analysis. The logo should be clean, modern, and memorable. Describe the concept behind each logo. Use a simple color palette. --style raw',
    description: 'Get several distinct and professional logo ideas for your brand.',
    author: MOCK_USERS[1],
    category: 'Art',
    tags: ['Logo Design', 'Branding', 'Minimalist'],
    upvotes: 190,
    downvotes: 6,
    createdAt: '2023-10-29T16:00:00Z',
    model: 'DALL-E',
    isPublic: true,
  },
  {
    id: 'p7',
    title: 'Watercolor Fantasy Landscape',
    prompt: 'whimsical watercolor painting of a glowing forest with giant mushrooms and sparkling streams, fireflies illuminating the path, vibrant and dreamy color palette, in the style of Studio Ghibli, detailed, high resolution',
    description: 'Create magical and enchanting landscapes with a beautiful watercolor aesthetic.',
    author: MOCK_USERS[1],
    category: 'Art',
    tags: ['Watercolor', 'Fantasy', 'Landscape', 'Studio Ghibli'],
    upvotes: 210,
    downvotes: 4,
    createdAt: '2023-10-30T12:00:00Z',
    model: 'MidJourney',
    isPublic: true,
  },
];

export const MOCK_COLLECTIONS: Collection[] = [
    {
        id: 'c1',
        name: 'Student Success Pack',
        description: 'A curated collection of essential prompts for academic success, from essay writing to creating engaging lesson plans.',
        creator: MOCK_USERS[0],
        price: 9.99,
        promptCount: 2,
        coverImage: 'https://picsum.photos/seed/c1/600/400',
        promptIds: ['p1', 'p5']
    },
    {
        id: 'c2',
        name: 'AI Artistry Master Pack',
        description: 'Unlock stunning AI art with this pack of 3 advanced prompts for MidJourney & DALL-E, covering various styles from sci-fi to branding and fantasy.',
        creator: MOCK_USERS[1],
        price: 19.99,
        promptCount: 3,
        coverImage: 'https://picsum.photos/seed/c2/600/400',
        promptIds: ['p2', 'p6', 'p7']
    },
    {
        id: 'c3',
        name: 'Developer & Marketing Starter Kit',
        description: 'Supercharge your projects with this diverse kit. Includes prompts for code refactoring and creating a full social media content calendar.',
        creator: MOCK_USERS[0],
        price: 14.99,
        promptCount: 2,
        coverImage: 'https://picsum.photos/seed/c3/600/400',
        promptIds: ['p3', 'p4']
    }
];